// Generated by Wrangler by running `wrangler types`

interface Env {
  SUPABASE_URL: string;
  SUPABASE_API_KEY: string;
  CLOUDFLARE_ACCOUNT_ID: string;
  R2_ACCESS_KEY_ID: string;
  R2_SECRET_ACCESS_KEY: string;
  R2_BUCKET_NAME: string;
  R2_PUBLIC_DOMAIN: string;
  FILES_BUCKET: string;
  R2_BUCKET: R2Bucket;
}
